sudo: required
language: php
services:
- mysql
php:
- '7.4'
- '7.3'
- '7.2'
- '5.6'
env:
- DB=mysql
before_install:
- sudo apt-get update
- sudo apt-get install -y python-software-properties
- LC_ALL=C.UTF-8 sudo add-apt-repository -y ppa:ondrej/php
- sudo apt-get update
- sudo apt-get install -y apt-transport-https apt-utils curl
- sudo apt-get install -y php$(phpenv version-name)-cli php$(phpenv version-name)-mysql php$(phpenv version-name)-snmp php$(phpenv version-name)-snmp php$(phpenv version-name)-gd php$(phpenv version-name)-sqlite3
- mkdir -p build/log
- mysql -e 'CREATE DATABASE weathermaptest; GRANT ALL ON weathermaptest.* TO weathermaptest@localhost
  identified by "weathermaptest"; FLUSH PRIVILEGES;'
- cp ./dev/ci/travis-composer.json ./composer.json

install:
- sudo ./dev/ci/travis-dependencies.sh
- composer install
addons:
  code_climate:
    repo_token: 858ba1f597a441ed0b8abfefb2db2ecc09309285da99bd165ebcf1b580ced776
  artifacts:
    debug: true
    target_paths:
    - /${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}
    paths:
    - ./travis-test-results-${TRAVIS_JOB_NUMBER}.zip
    s3_region: eu-west-1
  apt:
    packages:
    - imagemagick
    - rrdtool
    - xsltproc
    - fping
    - zip
before_script:
- mysql weathermaptest < test-suite/data/weathermap-empty.sql
after_script:
- vendor/bin/test-reporter
- php test-suite/make-failing-summary.php > test-suite/summary-failing.html
- zip -r travis-test-results-${TRAVIS_JOB_NUMBER}.zip test-suite
script:
- vendor/bin/parallel-lint --exclude app --exclude vendor .
- vendor/bin/phpunit --configuration build/phpunit.xml
